#ifndef GRAPHICSRENDERERSETTINGS_H
#define GRAPHICSRENDERERSETTINGS_H

#define GFX_RNDR_DEPTH_SORT_OPAQUE
#define GFX_RNDR_MAXIMUM_RENDER_DISTANCE 1000.f
///#define GFX_RNDR_FADE_DISTANCE 900.f

#endif
