#ifndef PHYSICSSETTINGS_H
#define PHYSICSSETTINGS_H

//#define PHYSICS_BODY_SCALE_INERTIA_TENSORS
#define PHYSICS_CONTACT_FRICTION_CONSTRAINT
#define PHYSICS_CONTACT_FRICTION_GEOMETRIC_AVERAGE
#define PHYSICS_SOLVER_GAUSS_SEIDEL

#endif
