#ifndef SHADERSETTINGS_H
#define SHADERSETTINGS_H

#ifndef SHADER_TEXTURE_SAMPLER_NUM
	#define SHADER_TEXTURE_SAMPLER_NUM 1
#endif
#ifndef SHADER_DEFAULT_BIAS_MIP
	#define SHADER_DEFAULT_BIAS_MIP 0.f
#endif
#ifndef SHADER_DEFAULT_BIAS_LOD
	#define SHADER_DEFAULT_BIAS_LOD 0
#endif

#define SHADER_SDF_MODE_DISABLED 0x00
#define SHADER_SDF_MODE_SDF      0x01
#define SHADER_SDF_MODE_MSDF     0x01

#endif
